### ISSUE TITLE
Cluster of several Zookeepers

### ISSUE THREAD

**Issue by guenhter** [AnsibleShipyard/ansible-zookeeper#43]
Hi,

how can it be managed to setup a cluster with e.g. 5 Zookeeper instances (everyone having a different id)?

regards
guenther

**Comment by ernestas-poskus** [comment]
Considering that you have ```zookeepers``` group in your inventory e.g.:

```
[zookeepers]
server[1:5]
```

```yaml
- name: Zookeeper
  hosts: zookeepers
  sudo: yes
  roles:
    - role: AnsibleShipyard.ansible-zookeeper
      zookeeper_version: 3.4.8
      apt_cache_timeout: 3600
      client_port: 2181
      init_limit: 5
      sync_limit: 2
      tick_time: 2000
      data_dir: /var/lib/zookeeper
      log_dir: /var/log/zookeeper
      zookeeper_dir: /opt/zookeeper-{{zookeeper_version}}
      zookeeper_hosts: "{{groups['zookeepers']}}"
```

and thats it
