### ISSUE TITLE
data_dir & log_dir not properly initialized for debian/ubuntu (non tarball deployment)

### ISSUE THREAD

**Issue by lhoss** [AnsibleShipyard/ansible-zookeeper#63]
Just found out on a deployment on Ubuntu 16.04
I will def. provide a PR fix  ASAP, by extracting the working task (from tarball.yml) out into `common-config.yml`

```
- name: "Create zookeeper {{item}} directory."
  file: path={{item}} state=directory owner=zookeeper group=zookeeper
  tags: bootstrap
  with_items:
    - "{{data_dir}}"
    - "{{log_dir}}"
```

Actually I'ld like todo the same with (not too old) task/feature (also in tarball):
```
- name: Add zookeeper's bin dir to the PATH
  copy: content="export PATH=$PATH:{{zookeeper_dir}}/bin" dest="/etc/profile.d/zookeeper_path.sh" mode=755
  when: zookeeper_register_path_env
```

@ernestas-poskus ok for you todo  in the same PR ?

ps: Finally we would like to apply more cleanups in the role (sep. PR!), especially renaming those vars without `zookeeper_` prefix. 
Again the question howto best keep downward compatibility (after renaming). 
I'ld propose to add an info block in the README incl. howto map from new->old vars (rather than add an automatic mapping in the default vars)
```
data_dir: zookeeper_data_dir
log_dir: zookeeper_ log_dir
```
